Add sdlatomic.inc
PascalGameDevelopment/SDL2-for-Pascal pull request #41
Opened 2022-04-13 18:08 UTC by suve

This patch adds `units/sdlatomic.inc`, based on `SDL_atomic.h`.

The `SDL_CompilerBarrier()` function is missing because it's actually [a C macro](https://github.com/libsdl-org/SDL/blob/b424665e0899769b200231ba943353a5fee1b6b6/include/SDL_atomic.h#L147) that evaluates differently based on the compiler. We could, alternatively, make this a Pascal function that matches the macro's [generic/fallback version](https://github.com/libsdl-org/SDL/blob/b424665e0899769b200231ba943353a5fee1b6b6/include/SDL_atomic.h#L158).

2022-04-14 01:18 UTC, Free-Pascal-meets-SDL-Website commented
Thanks, great work!

Here are some thoughts I'd like to share/discuss with you:

**Code style hints**
To be in accordance with the cody style guidelines, which states to stay as close as possible with the C code, I would suggest:
1) Line 42: Rename `TSDL_Atomic` into `TSDL_atomic_t` and lower-case `Value` (see [ref](https://github.com/libsdl-org/SDL/blob/b424665e0899769b200231ba943353a5fee1b6b6/include/SDL_atomic.h#L244))  + also adapt all parameter lists consequently
2) Line 49 + 87: Rename param. list (`oldValue` into `oldval`, ...) (see [ref](https://github.com/libsdl-org/SDL/blob/b424665e0899769b200231ba943353a5fee1b6b6/include/SDL_atomic.h#L263))
3) Many param lists: Rename `atomic` by `a` and `value` by `v`.

**Macro issue**
I like the idea to have a fallback version. It should be accompanied with a comment explanation why we just have this fallback. The comment should be marked by a preceding _Conv.:_ or something to distinguish this comment from translated comments from the C source.
Same goes for the other macros like `SDL_MemoryBarrierRelease` and the likes.

**Version tag**
The version tag of the inc-file should indicate against what version the file has been checked, so if you checked and updated the file according to SDL version 2.0.20, the tag should be 2.0.20, although the file itself has been updated the last time in version 2.0.6. This way we can quickly identify files which where never checked (or a long time ago) against a recent SDL version.

2022-04-14 01:22 UTC, Free-Pascal-meets-SDL-Website requested changes
Please see [conversation](https://github.com/PascalGameDevelopment/SDL2-for-Pascal/pull/41#issuecomment-1098617901) for details.

2022-04-15 08:10 UTC, suve commented
Regarding `SDL_CompilerBarrier()`, we could make this call [`System.ReadWriteBarrier()`](https://www.freepascal.org/docs-html/current/rtl/system/readwritebarrier.html) on FPC.

As for the version tag, all of #37, #38, #39, #40 and #41 are up-to-date against SDL 2.0.20.

2022-04-17 01:16 UTC, Free-Pascal-meets-SDL-Website commented
> Regarding `SDL_CompilerBarrier()`, we could make this call [`System.ReadWriteBarrier()`](https://www.freepascal.org/docs-html/current/rtl/system/readwritebarrier.html) on FPC.

I really like this idea! I made a search for Delphi but didn't find equivalent functions. Maybe for Delphi/other compilers we implement the generic version.

> As for the version tag, all of #37, #38, #39, #40 and #41 are up-to-date against SDL 2.0.20.

That is great!

Will you update this PR or should I do it? Please let me know.

2022-06-17 14:17 UTC, merged

2022-06-17 14:17 UTC, Free-Pascal-meets-SDL-Website commented
Thanks again, I'll merge this now and add a todo about the code styling for later updates.

Best regards